name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Attest Plugin Artifacts
        uses: actions/attest-build-provenance@v4
        with:
          files: |
            main.js
            manifest.json
            styles.css
          
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            main.js
            manifest.json
            styles.css